# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: gnuton/vitasdk-docker:latest

steps:
- script: sudo apt-get install -qq -y pkg-config
  displayName: 'Install extra dependencies'

- script: sudo apt-get install -qq -y libc6-dev-i386
  displayName: 'Install 32 bit libraries'

- script: |
    git clone https://github.com/xerpi/libvita2d
    sudo -E cp libvita2d/libvita2d/include/utils.h $VITASDK/arm-vita-eabi/include/utils.h
  displayName: 'Get vita2d extra headers'

- script: |
    make clean
    make -j$(nproc)
  displayName: 'Build (Standard)'
  
- script: |
    make clean
    make SYS_APP_MODE=1 -j$(nproc)
  displayName: 'Build (Sys App)'

- task: GitHubRelease@0
  inputs:
    gitHubConnection: release
    repositoryName: Rinnegatamante/lpp-vita
    tagSource: manual
    tag: Nightly
    action: edit
    assets: |
      eboot_safe.bin
      eboot_unsafe.bin
      eboot_unsafe_sys.bin
  displayName: 'Deploy artifacts'
